export const AUTH_LOGOUT_ACTION = 'AUTH_LOGOUT_ACTION';

export const AUTH_REMOVE_TOKEN_MUTATION = 'AUTH_REMOVE_TOKEN_MUTATION';

export default {
  AUTH_LOGOUT_ACTION,
  AUTH_REMOVE_TOKEN_MUTATION,
};
