export const AUTH_LOGOUT_ACTION = 'AUTH_LOGOUT_ACTION';
export const AUTH_LOGIN_ACTION = 'AUTH_LOGIN_ACTION';
export const AUTH_GET_USER_ACTION = 'AUTH_GET_USER_ACTION';

export const AUTH_REMOVE_USER_MUTATION = 'AUTH_REMOVE_USER_MUTATION';
export const AUTH_SET_USER_MUTATION = 'AUTH_SET_USER_MUTATION';
export const AUTH_SET_ERRORS_MUTATION = 'AUTH_SET_ERRORS_MUTATION';
export const AUTH_RESET_ERRORS_MUTATION = 'AUTH_RESET_ERRORS_MUTATION';

export default {
  AUTH_LOGIN_ACTION,
  AUTH_LOGOUT_ACTION,
  AUTH_GET_USER_ACTION,
  AUTH_REMOVE_USER_MUTATION,
  AUTH_SET_USER_MUTATION,
  AUTH_SET_ERRORS_MUTATION,
  AUTH_RESET_ERRORS_MUTATION,
};
