export const TODOS_GET_ITEMS_ACTION = 'TODOS_GET_ITEMS_ACTION';
export const TODOS_ADD_ITEM_ACTION = 'TODOS_ADD_ITEM_ACTION';
export const TODOS_DELETE_ITEM_ACTION = 'TODOS_DELETE_ITEM_ACTION';
export const TODOS_UPDATE_ITEM_ACTION = 'TODOS_UPDATE_ITEM_ACTION';

export const TODOS_SET_ITEMS_MUTATION = 'TODOS_SET_ITEMS_MUTATION';
export const TODOS_ADD_ITEM_MUTATION = 'TODOS_ADD_ITEM_MUTATION';
export const TODOS_DELETE_ITEM_MUTATION = 'TODOS_DELETE_ITEM_MUTATION';
export const TODOS_UPDATE_ITEM_MUTATION = 'TODOS_UPDATE_ITEM_MUTATION';
export const TODOS_SET_FILTER_MUTATION = 'TODOS_SET_FILTER_MUTATION';

export default {
  TODOS_GET_ITEMS_ACTION,
  TODOS_ADD_ITEM_ACTION,
  TODOS_DELETE_ITEM_ACTION,
  TODOS_UPDATE_ITEM_ACTION,
  TODOS_SET_ITEMS_MUTATION,
  TODOS_ADD_ITEM_MUTATION,
  TODOS_DELETE_ITEM_MUTATION,
  TODOS_UPDATE_ITEM_MUTATION,
  TODOS_SET_FILTER_MUTATION,
};
